language: node_js
node_js:
  - "node"
  - "6"
  - "4"
  
script:
  - npm run-script build
  - echo '!*bundles*/*/*.min.css' >> .gitignore
  - echo '!*bundles*/*/*.min.js' >> .gitignore
  - echo '!*bundles*/*/*.html' >> .gitignore
  #- find desktop.bundles/ \( -name '*.min.css' -or -name '*.html' -or -name '*.min.js' \) -exec mv {} . \;
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    node_js: "node"
